### ISSUE TITLE
 Error: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by dat-nguyen96** [krzysztoffiok/TextGuide#1]
To fix this error, just simply comment this line #df = df.set_index('check_sum', drop=False) in the read_data function of utils.py from textguide

**Comment by krzysztoffiok** [comment]
Thank you @dat-nguyen96 
This error is caused by the fact of having duplicated instances in the data set created by Text Guide. This means that either there were duplicated instances in the original data set, or duplicates were created by Text Guide. The latter can happen especially when in the original data set similar instances exist.

**Comment by krzysztoffiok** [comment]
Explained, the original behavior can be easily modified as proposed.
